<?php

define('QUICKTEL_SMS_GATE_HTTP', 'http://service.qtelecom.ru/public/http/');
define('QUICKTEL_SMS_GATE_HTTPS', 'https://go.qtelecom.ru/public/http/');

/**
 * hook_menu() implementation
 */
function quicktel_sms_menu() {
  $items = array();

  //config page
  $items['admin/config/services/quicktel-sms'] = array(
    'title' => 'Quick Telecom SMS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_quicktel_sms_admin_page'),
    'access arguments' => array('administer quicktel sms'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
} //quicktel_sms_menu


/**
 *
 * hook_permission() implementation
 *
 * @return array
 */
function quicktel_sms_permission() {
  return array(
    'administer quicktel sms' => array(
      'title' => t('Administer Quicktel'),
      'description' => t('Administer Quick Telecom SMS gateway'),
    ),
  );
} //quicktel_sms_permission


/**
 *
 * Generates admin form for module
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function _quicktel_sms_admin_page($form, &$form_state) {
  //get balance
  $response = _quicktel_sms_send_request('balance');

  if (isset($response->balance)) {
    //show balance
    $balance = (string)$response->balance->AGT_BALANCE;
    $overdraft = (string)$response->balance->OVERDRAFT;
    $form['quicktel_sms_balance'] = array(
      '#type' => 'markup',
      '#markup' => "<p>Balance: $balance, Overdraft: $overdraft </p>",
    );
  } else if (isset($response->errors)) {
    //we have an error getting balance, display it
    drupal_set_message((string)$response->errors->error, 'error');
  }

  //get settings
  $form['quicktel_sms_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Quicktel Login'),
    '#default_value' => variable_get('quicktel_sms_user', ''),
    '#required' => TRUE,
    '#description' => t('Login to Quick Telecom service (as provided by the service)'),
  );

  $form['quicktel_sms_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Quicktel password'),
    '#default_value' => variable_get('quicktel_sms_password', ''),
    '#required' => TRUE,
    '#description' => t('Password to Quick Telecom service (as provided by the service)'),
  );

  $form['quicktel_sms_https'] = array(
    '#type' => 'checkbox',
    '#title' => 'HTTPS',
    '#default_value' => variable_get('quicktel_sms_https', 1),
  );

  return system_settings_form($form);
} //_quicktel_sms_admin_page


/**
 *
 * Sends a request with type given
 *
 * @param string $request_type type of request: balance, ...
 * @return \SimpleXMLElement or FALSE if error parsing XML
 */
function _quicktel_sms_send_request($request_type = '') {
  $request = array();

  _quicktel_sms_add_authorization($request);

  //add request-specific data
  //TODO decouple type-specific logic
  switch ($request_type) {
    case 'balance':
      $request['action'] = 'balance';
      break;
    default:
      break;
  }

  $headers = array(
    'Content-Type' => 'application/x-www-form-urlencoded',
  );
  $options = array(
    'headers' => $headers,
    'method' => 'POST',
    'data' => http_build_query($request),
  );

  //check which url to use
  $request_url = (variable_get('quicktel_sms_https', 1)) ? QUICKTEL_SMS_GATE_HTTPS : QUICKTEL_SMS_GATE_HTTP;

  $response = drupal_http_request($request_url, $options);
  $response->data = gzdecode($response->data);

  return simplexml_load_string($response->data);
} //_quicktel_sms_send_request


/**
 *
 * Add authorization data (login, password) to the request
 *
 * @param $request
 */
function _quicktel_sms_add_authorization(&$request) {
  $user = variable_get('quicktel_sms_user', '');
  $password = variable_get('quicktel_sms_password', '');

  if ($user && $password) {
    $request['user'] = $user;
    $request['pass'] = $password;
  }
} //_quicktel_sms_add_authorization
